apiVersion: repositories.flare.engineering/v1alpha1
kind: Repository
metadata:
  name: ground-dev-tag
spec:
  description: Repository reference that will trigger on tags that end with -dev-ga
  remote:
    private:
      name: flare-example/ground
      integration: github
      trigger:
        type: tag
        pattern: .*(-dev-ga)$
