apiVersion: repositories.flare.engineering/v1alpha1
kind: Repository
metadata:
  name: service-chart-branches
spec:
  description: Repository reference that will trigger on any branch commit
  remote:
    private:
      name: flare-example/service-chart
      integration: github
      trigger:
        type: branch
        branch: .*
