# custom health checks for the mesh ingress proxies
{{- with .Values.ingress.backend }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  namespace: {{ $.Release.Namespace }}
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP
  timeoutSec: {{ .timeoutSec }}
  cdn:
    enabled: {{ .cdn.enabled }}
    cachePolicy:
      includeHost: {{ .cdn.cachePolicy.includeHost }}
      includeProtocol: {{ .cdn.cachePolicy.includeProtocol }}
      includeQueryString: {{ .cdn.cachePolicy.includeQueryString }}
  securityPolicy:
    {{- range $i, $policy := .policies }}
    name: {{ $policy }}
    {{- end }}
{{- end }}
