apiVersion: v1
kind: Service
metadata:
  name: my-go-service
spec:
  type: ClusterIP
  selector:
    app: my-go-service
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
